BlueBrain/neurodamus

neurodamus/core/configuration.py, neurodamus/node.py
This PR splits the `enable_reports` function into smaller ones, making it easier to maintain and opening the way for further refactoring.
=> Breaking enable_reports into pieces

.gitlab-ci.yml, neurodamus/io/sonata_config.py
This PR solves 2 issues:
1. It reverts https://github.com/BlueBrain/neurodamus/commit/0cc296110416d3d4095dbb98590857b7f0877cd9 to preserve the order of stimulus injection
2. Sets the proper branch name of neurodamus to blueconfigs
It seems that in the PR https://github.com/BlueBrain/neurodamus/pull/30 the `blueconfigs` CI didn't get launched with the proper `neurodamus` branch as can be seen from https://bbpgitlab.epfl.ch/hpc/sim/blueconfigs/-/jobs/850462 where the `py-neurodamus` branch is not set by `spack`.
And the PR also reverts the previous commit to preserve the order of stimulus injections read from the sonata config file.
Pass to `blueconfigs` trigger the proper env variable to fix `2.`
Should be tested by the CI of this PR in the `setup_spack` stage
=> Preserve the order of stimulus injection & CI fix

neurodamus/replay.py, tests/scientific/test_replay.py, tests/test_replay_manager.py
Replay from Sonata spikes suffers from the 0/1-based gids mismatch. We Fix that
Changed the tests accordingly
=> From Sonata 0-based spikes to 1-based

tests/test_multicycle_runs.py, tests/test_neuromodulation.py
The change on the dynamic MPI library introduced by the NEURON release 9.0.a10 has impacted some of our unit tests calling `Neurodamus` class with CORENEURON. While pending for a fix from NEURON, we skip these tests to unlock the pipeline.
=> Skip CORENEURON unit tests pending for a fix from NEURON

neurodamus/ngv.py, tests/test_ngv.py
Gids are 0-based in sonata circuits and neurodamus converts them to 1-based internally and passes to NEURON. When using libsonata API to read sonata circuits, the input gids should be 0-based. This PR fixes GlioVascularManager in ngv that will use 0-based gids to read the gliovascular edge files.
In ngv.py: Convert to 0-based when calling libsonata API, i.e. self._gliovascular.afferent_edges(astro_id-1)
Enable and correct test_ngv.py. It was skipped because of BBPBGLIB-1039.
=> Use 0-based gid for reading GlioVascular sonata edges file

neurodamus/commands.py
After a recent change, the logging level CLI option `--verbose` and `--debug` don't work any more. This PR fixes the logging level of the simulation. 
In `Neurodamus::__init__`, the `logging_level` is now the 4th argument.  In `command.py`, when instantiating the `Neurodamus` class, use the keyword argument to set the logging level correctly.
=> Propagate the log level correctly from the CLI option to Neurodamus class

neurodamus/replay.py
"special" binaries which flushes denormal results to zero triggers the numpy warning for subnormal in every rank
after "import h5py". Neurodamus had a filter to ignore this type of warning, but it is insufficient after the recent change of adding "import h5py" at the top of replay.py. We have flooded warnings at the beginning of the simulation before instantiating neuron. This PR changes to import h5py in the function call to make the filter work again. It also ensures that we are loading the right h5py version.
In replay.py, import h5py in the function call instead of at the top.
Existing tests
=> import h5py in the function call to filter numpy warnings

.github/workflows/simulation_test.yml
A small change. Cloning NEURON takes some time and space. This PR tells the CI workflow not to fetch the whole git history.
I just added `--depth=1` to git clone commands.
Instead of `90k` it retrieves `3k` objects for NEURON.
```bash
Cloning into 'nrn'...                                                                                                                                                                                                                
remote: Enumerating objects: 90968, done. 
```
```bash
Cloning into 'nrn'...                                                                                                                                                                                                                
remote: Enumerating objects: 2930, done.   
```
=> ci git clone set --depth=1

neurodamus/core/_shmutils.py, neurodamus/utils/memory.py
Memory usage statistic of MPI tasks is useful when balancing work on a per task level. However, for estimating how close one is to going OOM, the min, max and average don't provide precise information. Instead it would be useful to see statistics of the memory usage of each compute node.
=> Print statistics of nodewise memory usage.

core/mod/ALU.mod
**Context**: We'd like to make `non_owning_identifier` a non-trivial class. Because this will allow us to make it reference counted. The implication is that it'll be  important that it's initialized and destroyed properly.
**Problem**: ALU.mod contain C code which `malloc`s `data_handle`s, but `data_handle`s contain a `non_owning_identifier`. Hence, `data_handle`s must be initialized and destroyed properly.
**Twist**: When install NEURON via `pip install` then `nrnivmodl` will generate a C file `ALU.c` which means we can't use `new` and `delete[]`.
**Fix**: Closer inspection of ALU.mod shows that it already requires a C++ compiler when `NRN_MECHANISM_DATA_IS_SOA` is defined. Since this covers the cases in which we need a C++ compiler, we use this macro to conditionally either use …
=> Modernize ALU.

.gitlab-ci.yml
We're getting dev build containers on main, where we only want actual version containers.
Todo:
Webhook was upated - I tried on a private repository first, sync with gitlab didn't break there.
Building containers manually for older tags throught he pipeline is not possible (the pipeline configuration just wasn't there), that will only be possible once everything is in place.
This PR will check whether we're on a tagged commit before building the docker container. If not, we don't build the container.
N/A
* ~~[ ] Coding style (imports, function length, New functions, classes or files) are good~~
* ~~[ ] Unit/Scientific test added~~
* ~~[ ] Updated Readme, in-code, developer documentation~~
=> Don't build containers unless we're on a tagged commit

.github/workflows/simulation_test.yml
Running the simulation workflow on pull request was deemed overkill in the neurodamus sync, so we're moving it to a nightly run.
Changed workflow trigger - if necessary it can still be adjusted.
n/a
* ~~[ ] Coding style (imports, function length, New functions, classes or files) are good~~
* ~~[ ] Unit/Scientific test added~~
* ~~[ ] Updated Readme, in-code, developer documentation~~
=> Run the simulation test nightly instead of on PRs and main

neurodamus/connection_manager.py, neurodamus/io/sonata_config.py, neurodamus/node.py, tests/test_synapses.py
Address BBPBGLIB-1061 partially, ensuring, for the moment that we instantiate all projections.
- Consider only some specifically-named edge populations as internal connectivity
- Other populations shall go as projections
Not all populations should go as projections since circuits still respect order, which is important for the case of e.g. NGV.
Existing CI tests
=> BBPBGLIB-1061 SONATA conf: Dont map to internal connectivity

neurodamus/node.py
This will help us see when and if users set the report dt < 0.1 that when using CoreNEURON, it causes some performance degradation as reported in [REP-68](https://bbpteam.epfl.ch/project/issues/browse/REP-68)
=> Add report dt to the logging

neurodamus/connection_manager.py, neurodamus/core/nodeset.py
Addresses HPCTM-1824 and HPCTM-1770.
During the synapse configure, a numpy array was created with the gids of the src_target nodeset for every connection. Then a numpy.searchsorted was checking if a certain gid was in that array. This was taking a long time (~1h) when having a lot of connections (~2e8).
The idea is to create a set with the target gids in order to improve the lookup time.
=> [HPCTM-1824] Introducing a temporary set for faster lookup in the src_target gids

neurodamus/core/configuration.py, neurodamus/node.py
The simulation was crashing in certain situations when using nrnPath="<NONE>", specifically in the load balancing and loading nodes in a ncs circuit.
To avoid this in the load balancing, we use the CircuitPath instead.
When using ncs circuits, we raise an ConfigurationError exception at the beginning of the simulation.
=> [BBPBGLIB-1055] Support "<NONE>" as nrnPath

neurodamus/replay.py
Use libsonata instead of h5py in order to read the spikes.
The new 'get_dict()' method is used to retrieve the 'node_ids' and the 'timestamps' of a spikes report. (https://github.com/BlueBrain/libsonata/pull/285)
=> [BBPBGLIB-1044] Use libsonata to read the spikes

docs/architecture.rst, neurodamus/cell_distributor.py, neurodamus/node.py, neurodamus/utils/memory.py
Introduces nodes suggestions for users. 
This functionality is one of the main results that should come out of the introducing of the dry run workflow.
Nodes suggestion is calculated taking in mind the amount of memory present in the current machine where the code has been run. It also takes into consideration the variable amount of overhead necessary dependent on the amount of ranks used for the execution.
Most of the changes are independent of the main workflow and only touch the dry-run workflow. A prompt has been added at the end of any dry run workflow to provide a suggestion for user on how many nodes are needed in order to have a reasonable amount of memory available to run the simulation.
Since the MR just introduces a small text prompt for the user, no tests are necessary.
Full …
=> [BBPBGLIB-1069] Added nodes suggestions and more improvements

neurodamus/connection_manager.py, neurodamus/morphio_wrapper.py, neurodamus/ngv.py, neurodamus/node.py
Even with a small execution we were hitting
```
323 NEURON: gid=1000000 already exists on this process as an output port
```
When outputting some debug it turned out that the post synaptic edge index was not being taken into account for the NGV netcon id. Therefore the id collision was almost certain.
Turns out the `load_offset` property was not always set to True in the connection manager. 
This likely happens since in newer Sonata circuits there might be no internal connectivity, where such setting was being applied.
With the current readers we always have synapse ids. So we could generalize the concept and set
- All managers to load their synapse indices (ctor arg)
- All except NGV which will never require them, so we explicitly disabled.
- Setting applied even for connection managers …
=> BBPBGLIB-1076 Make all edge managers set load_offsets at init

.gitlab-ci.yml
Gitlab workflows were not triggering on tag creation.
The job rules were correct, but the workflow rule for this scenario was missing.
=> Workflow rule: CI_COMMIT_TAG

.gitlab-ci.yml, README.rst
Containers automatically take a specific version of libsonata, libsonata-report and neuron. Sometimes a user wants to build with a specific version of one or more of these dependencies.
* Allow setting the variables that determine which dependency version to use manually
* If set, also require a container version to be specified to avoid "polluting" the official container builds
=> Manual container versions

neurodamus/target_manager.py, tests/test_nodeset_target.py
Seen in some simulations, when a NodeSet taget doesn't contain any cell by its (bad) definition, `get_local_gids` raises an error from `numpy.concatenate(tuple([]))`. This PR sets an protection for this case.
In the definition of `NodesetTarget::get_local_gids`, return `numpy.empty(0)` if the array to be concatenated is empty
A new unit test `test_nodeset_target.py`
=> protect numpy.concatenate empty tuple in get_local_gids

neurodamus/metype.py, tests/test_error_handling.py
The current error handling between Neuron and neurodamus is as such:
* For a single process, Neuron (`hoc_execerror_mes`) throws a RuntimeError and neurodamus handles it (in `commands.py`) and aborts the process.
* For multiple processes, Neuron calls `nrnmpi_abort` when an error is raised in any rank. The exception can not be caught in neurodamus before the processes end.
As meaningful error msg is  requested in [BBPP134-1022], this PR sets Neuron not call `nrnmpi_abort` internally but passes the exception to be handled later in neurodamus.
In `metype.py`, set the flag `old_flag = Nd.pc.mpiabort_on_error(0)` before the neuron process and revert it afterwards. When an exception from Neuron is caught by neurodamus, neurodamus will improve the error msg with more details and raise again. …
=> [BBPP134-1022] Handling exceptions from NEURON during emodel loading

neurodamus/core/_neuron.py, neurodamus/core/configuration.py, tests/test_loadbalance.py
Save the default `dt` from `NEURON` and use it when generating the `mcomplex` file with `ExperimentalMechComplex`
This PR solves the issue described in https://github.com/neuronsimulator/nrn/issues/2038
First we save the original `dt` value of `NEURON` in the `SimConfig`. Then in the function that generates the complexity of each cell we set the `dt` to the original `NEURON` value, which normally should be `0.025`.
Removed the explicit setting of `dt` to `0.025` in the load balance unit test
=> Use default dt value of NEURON in WholeCell load balancing

neurodamus/io/sonata_config.py, tests/test_sonata_config.py
One SONATA parameter in the input section is  "amp_cv" while neurodamus internally requires "AmpCV".  In `sonata_config.py`, the default translation algo `snake_to_camel` is not sufficient, so this PR adds a manual conversion. 
In `sonata_config.py`, add the manual conversion in a dict.
Add `test_parse_inputs` in `test_sonata_config.py`.
=> Fix conversion from sonata parameter to neurodamus internal key : amp_cv -> AmpCV

.github/workflows/simulation_test.yml, docker/build_neurodamus.sh
Add `--only-neuron` CLI argument from the [Spack recipe](https://github.com/BlueBrain/spack/pull/2198/files)
Add option for building MOD files only with NEURON
`build_neurodamus.sh` script that should be the same as the `Spack` recipe of `Neurodamus`
=> Update build_neurodamus.sh with `--only-neuron`

neurodamus/connection_manager.py, neurodamus/node.py, neurodamus/utils/memory.py
When using a different number of ranks it was noticeable a slightly different count in the number of synapses.
It turned out one was retrieving and counting synapses for the same gid under some circumstances when configure blocks would overlap.
The bug is fixed by
- keeping track of gids for which one has already retrieved synapse counts.
- Exclude those when fetching and adding up the synapses counts per type to the global counter
- Sort results order to improve comparison
Running on a testing simulation 
- 400 cells and 18 Configure blocks  (sonata-quick-v5-plasticity)
- 1 vs 40 ranks (previously results would be different)
=> Fix bug with duplicate count of synapses

neurodamus/connection_manager.py, neurodamus/utils/pyutils.py
Up until now for the purposes of counting in the dry run mode, all synapses were loaded at the same time. This started to create some issues when moving to very large circuit where the execution would consistently run out of memory.
This MR tries to fix this issue by chunking the loading in blocks of 100 cells at a time in order not to spend the whole memory.
The changes are relatively small and include the adding of a small generator for chunking ranges in the util section, and a small rework of the loading synapses block to load cells in predefined ranges.
No new functionality so no new tests are necessary.
=> Implement chunking mechanism for loading synapses in dryrun mode

neurodamus/cell_distributor.py, neurodamus/core/configuration.py, neurodamus/node.py, tests/integration-e2e/test_loadbalance.py
A number of Sonata circuits wouldn't use the load balance object, even though it had been built. See BBPBGLIB-1027
The issue stems from the fact that we compute load balance for a single population, but there was no way to identify which one. That information is required when later instantiating the circuit.
This PR has two sides of it. 
1. As an interim solution before we do load balance for all circuits, we pass the single load_balance object to all.
2. An actual improvement to `LoadBalance`, making it aware of its population, so that
- It won't mix and attempt creating a sub load balance out of another population
- We can easily identify if the load-balancer is suitable for a given circuit
Additionally we _stopped_ enabling `MultiSplit` automatically since it's a pretty advanced and …
=> [BBPBGLIB-1027] Fix: Load Balance with multi-populations

neurodamus/utils/memory.py
The function `malloc_trim` is specific to the GNU C library (glibc), so the call to it in `trim_memory` raises an `AttributeError` when running with other C library implementations (like the default one shipped with MacOS), which we now catch in the `except` block.
=> Fix call to `trim_memory` on non-GNU C libraries

neurodamus/utils/memory.py
MacOS does not use `/proc/`, and consequently Neurodamus crashes when attempting to determine the memory usage of the current process. The fix is to instead use the built-in [`resource`](https://docs.python.org/3/library/resource.html#resource-usage) module to get the memory usage, which works on both Linux and MacOS.
=> Fix memory usage reporting on MacOS

docs/development.rst, pyproject.toml, tests/scientific/test_projections.py
The last commit has blocked the simulations with BlueConfig files, so we are now only support SONATA data format. `mvdtool` is used for reading old mvd3 node files which is no longer needed and can be removed. 
This PR removes the dependency on `mvdtool` from the package configuration file (`pyproject.toml`). The relevant source functions will be cleaned up in the next PRs for further deprecating legacy/BlueConfig.   
Existing tests
=> Remove dependency on mvdtool

neurodamus/cell_distributor.py
Fixes longrun ci issue detected [here](https://bbpteam.epfl.ch/project/issues/browse/BBPBGLIB-1114).
Apply population offset to the gids before reading node file when reusing load balancer.
=> [BBPBGLIB-1114] Apply offset to the gids before reading node file

neurodamus/__init__.py, tests/integration-e2e/test_cli_opts.py
PR #115 has set checks on the command arguments so that positional arguments will be rejected. One of the unit test wasn't using the right `$NEURODAMUS_PYTHON/init.py` during the PR and thus failing now. 
And towards Python 3.12, `pkg_resources` will be deprecated and needs to be replaced. 
This PR fixed the unit test in `test_cli_opts.py` by correcting the argument to "--save=PATH".
And it replaces `pkg_resources.get_distribution` with `importlib.metadata.version` 
Existing tests
=> Fix unit tests

docs/architecture.rst, neurodamus/cell_distributor.py, neurodamus/commands.py, neurodamus/connection_manager.py, neurodamus/core/configuration.py, neurodamus/io/cell_readers.py, neurodamus/node.py, neurodamus/utils/memory.py, tests/integration-e2e/test_dry_run_worflow.py
This MR includes new mechanisms to generate a detailed load balancing using the memory estimates generated by the dry run. It distributes all the gids of the circuit to a number of ranks specified using the `--num-target-ranks` CLI flag taking care of distributing so that the allocation of each rank is balanced. The system is based on a greedy algorithm, assigning cells in blocks of 10 to the emptiest rank available at that moment.
It also includes automatic pickling and gzipping of the allocation dictionary to `allocation.pkl.gz` file. Loading of the generated load balance will be integrated in a future MR.
The MR briefly expands the capabilities of the dry run workflow with automatic load balancing and save to pickle file for future use. All the structure involved stay the same and no …
=> [BBPBGLIB-1102] Add load balance based on dry run estimate

.github/workflows/simulation_test.yml, neurodamus/io/sonata_config.py
The StrEnum type was introduced in python 3.11, so it was failing with previous python versions in the github actions.
In this PR, StrEnum is replaced by inheriting not only from enum but also from str.
=> StrEnum not working with older python versions

.github/workflows/publish_wheels.yml, CHANGES.rst
This PR fixes the fetching error seen in the GH workflow triggered by tag.
Remove "fetch-tags: true" in actions/checkout@v4
=> Fix fetching error in GH workflow triggered by tag and ChangeLog for 3.1.1

neurodamus/io/cell_readers.py
Fixes the crash when running sonataconf-sscx-O1 circuit on dry run as detailed in: https://bbpteam.epfl.ch/project/issues/browse/BBPBGLIB-1147
The fix is pretty simple and just involves iterating over the `meinfo.keys()` instead of the whole `gidvec` since not all the data metadata is loaded in dry run.
Just a simple fix.
No new testing needed.
=> [BBPGBLIB-1147] Fixes crashes with KeyError when running sonataconf-sscx-O1 circuit on dry run

neurodamus/connection_manager.py, neurodamus/io/synapse_reader.py, neurodamus/neuromodulation_manager.py, neurodamus/utils/memory.py
This MR solves https://bbpteam.epfl.ch/project/issues/browse/BBPBGLIB-1148
After investigation it seems that the `sonataconf-thalamus` circuit from `blueconfig` is including also gap junctions, that's why some of the connections were missing the `syn_type_id`.
Now the dry run can correctly treat gap junctions, count them and add to the synapse memory total. All the other types are also counted for future use.
Made the `get_counts` function work also when no `group_by` is specified, in which case it will return an int.
Added more branch and checks to take into account non-chemical connections.
No further testing needed.
=> [BBPGLIB-1148] Add support for gap junctions in dry run

neurodamus/data/hoc/neurodamus.hoc
After the removal of Report.hoc, there was still a reference in neurodamus.hoc. Remove it.
=> Remove Report.hoc reference

neurodamus/node.py, tests/integration-e2e/test_reports.py
Identical to PR #156, re-opening after being added to the Github organization
This PR solves
https://bbpteam.epfl.ch/project/issues/browse/BBPBGLIB-1153.
According to the SONATA specification, reports can be disabled with an optional enabled parameter in the config file. This option was already parsed, but not used to disable the reports.
A small change to the `enable_reports` method of the `Node` class, filtering the reports based on the `enabled` flag.
An integration test in `tests/integration-e2e/test_reports.py`, reusing part of the existing fixture there and reading the flag from a SONATA config file.
=> [BBPBGLIB-1153] Allow disabling reports from SONATA config

CONTRIBUTING.md
Identical to PR #157, re-opening after being added to the Github organization.
A small fix of a link in CONTRIBUTING.md that was still pointing to a markdown version of the README.
=> Fix dead link from CONTRIBUTING.md to README.rst

.github/workflows/simulation_test.yml, docker/README.md, tests/share/hoc/AMPANMDAHelper.hoc, tests/share/hoc/GABAABHelper.hoc
For neurodamus standalone build, the environment variable `CORENEURONLIB` should point to the coreneuron shared library in order to run CoreNEURON simulation. Without this variable, CoreNEURON may not load all the mechanism files correctly which has been seen in the docker container. 
Specify such information in the Docker README. Also add it in the GH workflow.
Current GH actions workflow.
=> [BBPBGLIB-1154] Add information about CORENEURONLIB in the Docker README

neurodamus/cell_distributor.py, tests/integration-e2e/test_loadbalance.py
After https://github.com/BlueBrain/neurodamus/pull/148, we are writing raw gids in `Nd.BalanceInfo` instead of final gids with offsets. Such change is missing in `record_spikes()` leading to no spike written in the report with NEURON while lb mode is enabled.
Fix in the function `cell_distributer.py: record_spikes`.
WIP
=> Fix record_spikes for load balancing

.github/workflows/simulation_test.yml
This PR speeds up the GitHub actions workflow by caching large packages to avoid rebuilding each time. Caches for NEURON, libsonata and libsonatareport are created based on the preliminary versions set as the workflow env variables, and will be reused in the later tests in case of the same versions. Users can overwrite the versions and rebuild the packages by commit msgs or using manual workflow_dispatch variables.
Github actions workflow `simulation_test.yaml`
=> Cache dependent packages in GH actions workflow

.github/workflows/simulation_test.yml, pyproject.toml
Improve github actions CI by adding python versions 3.9 to 3.12.
=> Add tests for python 3.9 to 3.12

neurodamus/commands.py, neurodamus/node.py
Neurodamus used to ensure `cleanup` was called by calling it from the destructor of the `Neurodamus` class.
However, depending on the python version, this could lead to crashes as some objects from `Node` eventually were already destroyed.
To workaround this problem, at some point we introduced the `cleanup_atexit` parameter which would skip over this procedure, and notably multiscale_run was using it. However this was not a solution as cleanup was not being called.
This PR fixes this long standing issue. Cleanup is now called directly from the top-level `run()` function. It can still be avoided if the user really wants to keep the data, with the parameter `cleanup=False`
CI is happy.
=> Avoid calling cleanup from destructor

.github/workflows/simulation_test.yml
This PR will enable the workflow when merging a branch to `main`. This will allow to build caches if needed for the default `main` branch immediately after merging. And PRs from other branches can restore the caches from `main` directly instead of building caches for each branch.
`simulation_test.yml`
=> Trigger workflow when pushing to main

tests/integration-e2e/test_cli_opts.py, tests/integration-e2e/test_plugin.py
Not all tests using subprocess would capture std streams. This means pytest could not handle their output properly. 
Fixes #51
Make all tests using subprocess capture std streams.
CI
=> Tests with subprocess should capture streams

docs/architecture.rst, neurodamus/utils/memory.py, tests/integration-e2e/test_dry_run_workflow.py
Add an estimate for the simulation memory usage. The estimate is simply calculated considering 2.5 times the total amount of memory estimated for cell + synapses. 
This factor is based on tests that we performed on a variety of circuit that seem to suggest that the ratio between the instantiation and the simulation tops at 2.5 times.
For more information see: https://bbpteam.epfl.ch/project/issues/browse/BBPBGLIB-1158
Just a simple add to already existing functions.
The modification will be tested during the already implemented integration tests for the dry run workflow.
=> [BBPBGLIB-1158] Add empirical mechanism to estimate simulation memory usage

neurodamus/connection.py, neurodamus/core/configuration.py, neurodamus/core/random.py, neurodamus/data/hoc/RNGSettings.hoc, neurodamus/stimulus_manager.py, tests/integration/test_neuron.py
Removing legacy RNGs and the ability to configure RNGs. Random123 is chosen everywhere as the only option.
RNG types differing from Random123 are no longer used and removed from everywhere (including configuration).
RNGSettings.hoc (removed RNGmode and all related constants), configuration.py, random.py, and corresponding usages.
Write a test that raises exception in attempt to configure RNG mode.
=> [BBPBGLIB-1122] Removing legacy RNGs, leaving only Random123

neurodamus/utils/timeit.py
In timeit.py logging, a Unicode symbol \u255a (╚ ) is used to draw the tree hierarchy of time intervals measured. For logging in Python, 'locale' encoding is used by default. If the terminal locale is set to anything except UTF-8 (e.g. 'latin-1'), Python's output codec cannot encode the symbol, and fails with UnicodeEncodeError exception.
The following solutions were considered:
1) Use an ASCII symbol instead of ╚, so it could work everywhere. 
The alternatives are "+", "=", and "L", but everything looks sort of ugly. We can also draw multi-line trees with |, + and -, but it takes a lot of more space and looks sort of ugly as well.
2) Force the UTF-8 encoded output.
Most terminals everywhere now support UTF-8. If they are misconfigured to other locale like latin-1, or genuinely do not …
=> [BBPBGLIB-739] Override UTF-8 for logging

docker/Dockerfile
Build both Neuron and libsonatareport out-of-tree, delete both source
and build directories after installing, in the same layer.
This should shrink our container download size a bit, as the current
container ships the Neuron source/build tree at a size of 1.9G.
=> Optimize Dockerfile a bit

neurodamus/connection.py, neurodamus/target_manager.py
User reported an error when creating synapse points on deleted sections. This kind of synapses should have been skipped by `Connection::add_synapses()`. This PR handles deleted sections correctly so that they are skipped.
In `target_manager.py` and `connection.py`, deleted sections are added to TPointList as `None` type, and skipped by `Connection::add_synapses()`.
n/a
=> [BBPBGLIB-1175] Handle deleted sections correctly

tests/simulations/ngv/circuit_config.json
Following the update of ngv/metabolism MOD files (https://github.com/BlueBrain/neurodamus-models/pull/14), the v10 emodels should be used in the ngv test. This PR updates the ngv test config file in the neurodamus unit tests.
Update `tests/simulations/ngv/circuit_config.json`, the same as `blueconfigs/sonataconf-quick-multiscale`.
The existing `tests/scientific-ngv`.
=> Update ngv test to use V10 emodels

neurodamus/commands.py, neurodamus/connection_manager.py, neurodamus/core/configuration.py, neurodamus/core/coreneuron_configuration.py, neurodamus/node.py, tests/integration-e2e/test_coreneuron_directmode.py
This PR implements a new CLI option "--coreneuron-direct-mode" that enables to run the coreneuron simulation using direct memory transferred from neuron, without writing intermediate model data to disk.
- When "--coreneuron-direct-mode", we set the Coreneuron parameter`coreneuron.file_mode=False`. 
- And Coreneuron writes the element reports but not the spike report.  So we still create `sim.conf`, `report.conf` and an empty folder `coreneuron_input`. The spike report is created explicitly in neurodamus via `sonata_spikes()` just like the Neuron runs.
- Enable fast membrane current calculation `Nd.cvode.use_fast_imem(1)` for  `i_membrane` and `lfp` reports.
New test file `test_coreneuron_directmode.py`.
The blueconfig pipeline tests with  "--coreneuron-direct-mode" enabled have been done …
=> [BBPBGLIB-854] Implement a CLI option to run coreneuron in direct mode without writing model data to disk

.github/workflows/simulation_test.yml
GitHub actions/python-versions has recently released python `3.12.5` as the default one for python 3.12. But our py3.12 cache was built with python `3.12.4`.  This inconsistency leads to the `pip install` failure in the workflow test for python 3.12.  
Specify python-version `3.12.5` in the workflow script.
Existing test.
=> Fix the Python 3.12 version inconsistency in GitHub actions cache 

neurodamus/cell_distributor.py, neurodamus/commands.py, neurodamus/connection.py, neurodamus/connection_manager.py, neurodamus/core/configuration.py, neurodamus/metype.py, neurodamus/utils/memory.py, tests/conftest.py, tests/integration-e2e/test_crashmode.py
Some simulations are pretty heavy, requiring a lot of nodes and time while, unfortunately, some problems only manifest in such very large scenarios. 
In order to improve the experience when testing new circuits, features or debugging a failure we introduce a new "Crash test" mode.
The new mode runs a simplified version of the circuit:
- Cells feature a single section
- Connections (between 2 cells) feature a single synapse (to the only section)
Therefore, while results are meaningless, the vast majority of Neurodamus internal machinery runs very quickly, allowing debug sessions to be orders of magnitude faster.
- Added new CLI option `--crash-test`
- Defined a new full-python cell featuring a single section, with all required attributes
- Implement a new `create_single()` function in …
=> Crash test mode

.github/workflows/simulation_test.yml
GHA setup-python, if not given the full python version, will install the latest patch.
However, since we cache venvs, things can go out of sync we and get errors like
```
/home/runner/work/neurodamus/neurodamus/venv/bin/python: bad interpreter: No such file or directory
```
Specify all Python versions precisely.
Pros: simple, consistent CI, more cache reuse
Cons: CI won't automatically pick newer python patch versions. (Is it a problem?)
Ci now passes
=> Pin Python versions

neurodamus/connection_manager.py, neurodamus/core/_utils.py, neurodamus/io/synapse_reader.py, tests/integration-e2e/test_crashmode.py
Speed up crash test mode to avoid loading as much data
- `SonataReader` to quickly find out cells for which we have no data and mark them with an empty dict
- For cells which have some data, in crash-test mode restrict the fetching edge index to only one (the first) per target cell. This operating could be done exclusively with numpy indexing operations, and is therefore fast.
=> Crash-test mode: Speed up synapse loading

neurodamus/io/synapse_reader.py, tests/integration-e2e/test_crashmode.py
Fix an issue reading extra properties for cells where there is no synapses.
Error:
```
conn_syn_params[name] = data[name]
E           KeyError: 'weight'
```
- After recent optimizations, we dont create empty base properties. Therefore, extended empty properties must not be created either. 
- We must ensure that when a gid is assigned EMPTY_DATA it is not considered, otherwise it would even ruin the shared empty dict. 
wip..
=> Synapse reading fixes

docs/api/neurodamus.io.rst, docs/api/neurodamus.rst, docs/api/neurodamus.utils.rst
After enabling the PR build for ReadtheDocs, we got doc build failure such as:
```
WARNING: Summarised items should not include the current module. Replace 'neurodamus.Neurodamus' with 'Neurodamus'. [autosummary.import_cycle]
WARNING: Summarised items should not include the current module. Replace 'neurodamus.Node' with 'Node'. [autosummary.import_cycle]
WARNING: Summarised items should not include the current module. Replace 'neurodamus.cell_distributor' with 'cell_distributor'. [autosummary.import_cycle]
...
```
This PR fixes the relevant doc files according to those warnings.
ReadtheDocs PR build
=> Fix ReadtheDocs PR build failure

neurodamus/cell_distributor.py, neurodamus/io/cell_readers.py, neurodamus/node.py, neurodamus/utils/memory.py, tests/integration-e2e/test_dry_run_workflow.py
As detailed in [https://bbpteam.epfl.ch/project/issues/browse/BBPBGLIB-1152](https://bbpteam.epfl.ch/project/issues/browse/BBPBGLIB-1152), multiple issues came up when trying to use the `neurodamus` memory load balance to run the MMB circuit.
In particular, the issues were a `list index out of range` error (that was caused by ranks/cycle sometimes not having any gids assigned) and an `Unpickling` error that is still misterious in its exact mechanics but that was seemingly caused by a corrupted broadcast of the allocation data.
This MR implements a huge reworking of the memory load balance workflow:
-  the `distribute_cells` function is now a subroutine of `distribute_cells_with_validation`. This new function implements directly a check to make sure all ranks/cycle have at least one gid …
=> Fix multiple issues with Memory Load Balance for MMB run

neurodamus/report.py, tests/integration-e2e/test_reports.py
Simulation was crashing when a point process was missing in a section in the context of summation reports.
Refactor the code to improve readability and avoid raising the exception to maintain consistency with CoreNEURON behavior
=> [REP-91] Avoid raising exception when point process is missing in a section

neurodamus/core/coreneuron_configuration.py, neurodamus/node.py
During CoreNEURON restore executions in multi-circuit simulations, reports fail to generate when circuits have multiple populations with different offsets. This occurs because the GIDs are saved in the report.conf without their proper population offsets during restore, as not all circuit population offsets are calculated at this stage. As a result, CoreNEURON ignores these reports due to GID mismatch with the original save execution.
To fix this, we now reuse the 'save' report.conf file and update only its tstop value, preserving the correct GID mappings.
=> [BBPBGLIB-1184] Fix CoreNEURON reports restore functionality

docs/index.rst, docs/memory_load_balance.rst
Adding tutorial for memory rebalance workflow
Just adds a single rst (and updates the index.rst) to explain how to use the memory rebalance workflow.
Just docs, no testing needed.
=> Update docs for memory rebalance

tools/rebalance-corenrn-data.py
With this change we introduce the possibility of using all data from a files.dat even if the header specifies a different count.
The usage is `--max-entries=0`
We also update the header in the output file accordingly, i.e. independently of the original header, the output header specifies the number of records as written in the file.
Tested with proj134/home/king/BBPP134-917/p_MultiCycle_Support
=> Rebalance tool: Fix record count. Enable using all files.dat entries

pyproject.toml
The last `docopt` release was in 2014, compare that to the more modern https://pypi.org/project/docopt-ng/
=> Replace unmaintained docopt with docopt-ng

neurodamus/core/configuration.py, tests/integration-e2e/test_cli_opts.py
Users should be able to run several save & restore processes in sequence for one simulation, explained in [wiki](https://github.com/BlueBrain/neurodamus/wiki/Using-CoreNeuron-in-Practice#using-save-restore-for-long-running-simulations). However, currently the restore uses the direct `coreneuron_input` folder from its `save` output directory, so it would lead to error `coreneuron_input dir not found` for multiple restores such as "save -> save & restore -> restore" because the 2nd restore only knows its previous save folder. Therefore, this PR tries to fix it by creating a symlink pointing to the `coreneuron_input` in the `save` output directory.  At the end of the last restore, this link will be removed by an existing function in `node.py`.
Create a `symlink` in `_coreneuron_params` for …
=> Fix Save/Restore coreneuron_input issue: create symlink to the save coreneuron_input folder

CHANGES.rst
Update change-log  with items since the last release
=> Updated change log for 3.7.0

.github/workflows/publish_wheels.yml, CHANGES.rst, README.rst
When publish release 3.7.0 to PyPI, we got the error `Username/Password authentication is no longer supported. Migrate to API  Tokens or Trusted Publishers instead`. This PR migrates to trusted publishers.
* Change in the github actions workflow for publishing wheels.
* Also update DOI badge in README.
=> [Release 3.7.1]: fix publishing to PyPI by using trusted publisher

.github/workflows/publish_wheels.yml, CHANGES.rst
3.7.1 was published without a source distribution. This PR adds publishing an sdist
* Change in the github actions workflow for publishing sdist
=> [Release 3.7.2]: make sure sdist is also published

.gitattributes
See https://github.com/neuronsimulator/nrn sidebar.
=> NEURON's NMODL language should now be properly recognized by GitHub.
